### ISSUE TITLE
Storage locations

### ISSUE THREAD

**Issue by danbradham** [construct-org/construct#15]
Currently construct only supports one storage location via CONSTRUCT_ROOT or the ROOT config key.

A better solution would be to create a Storage api and a STORAGE config section.
```
 STORAGE:
     primary:
         path:
             win: C:/projects
             linux: /projects
             mac: /projects
    renders:
        path:
            win: C:/renders
            linux: /renders
            mac: /renders
    default: primary
```

Storage can then be used in templates.
```
shot: {storage}/{project}/sequences/{sequence}/{shot}
shot_render: {storage}/{project}/sequences/{sequence}/{shot}
```
