### ISSUE TITLE
Refactor Project and Asset data

### ISSUE THREAD

**Issue by danbradham** [construct-org/construct#62]
### 1. Project Schema
Include more data at the project level to prevent having to query the filesystem as frequently. Storing a manifest of assets in particular should alleviate our current issues with performance once a project reaches a sufficient size. 

Introduce the concept of bins to the project. Bins are like sub-projects that can have their own unique set of assets and shots. This is an invaluable concept considering that some projects may contain separate shots for multiple products. For instance one project for a client's product launch may include 15 second spots for a phone, tablet, and speaker etc. Such a project might have bins like Phone15, Tablet15, and Speaker15. In these cases a "Common" bin could be created that stores assets shared by all of the deliverables.

```
_id (uuid) - Id of this project
name (string) - Name of the project
created_at (datetime) - Date of creation
created_by (string) - Username
fps (float): Frame rate as a float value
software (dict) - Software available for this project
tree (dict) - Project filepath templates
bins (dict) - Sub projects / folders
asset_types (dict) - Asset types this project contains
task_types (dict) - Available tasks for this project
bins (dict) - Manifest of project bins - each can contain their own assets and shots
assets (dict) - Manifest of assets
```

#### Example Project
```
_id: uuid
name: Project Name
description: Description of project
created_at: Creation Date
created_by: User
fps: 24.0

software:
  maya: {...}
  nuke: {...}
  houdini: {...}
  ...

tree:
  bin: '{project}/{bin}'
  asset: '{project}/{bin}/{asset_type}/{asset}'
  workspace: '{project}/{bin}/{asset_type}/{asset}/{task}/work/{host}'
  publish: '{project}/{bin}/{asset_type}/{asset}/{task}/publish/{ext}'
  review: '{project}/review/{task}/{bin}/{asset_type}/{asset}'
  render: '{project}/renders/{task}/{bin}/{asset_type}/{asset}'
  file: '{task}_{name}_v{version}.{ext}'
  file_sequence: '{task}_{name}_v{version}.{frame}.{ext}'
  ...

asset_types:
  asset:
    plural: assets
    icon: asset.svg
  shot:
    plural: shots
    icon: shot.svg
  ...

task_types:
  design:
    short: dsn
    icon: design.svg
    order: 0
  model:
    short: mdl
    icon: model.svg
    order: 1
  texture:
    short: tx
    icon: texture.svg
    order: 2
  shade:
    short: shd
    icon: shade.svg
    order: 3
  rig:
    short: rig
    icon: rig.svg
    order: 4
  animation:
    short: anim
    icon: anim.svg
    order: 5
  fx:
    short: fx
    icon: fx.svg
    order: 6
  lighting:
    short: lgt
    icon: light.svg
    order: 7
  compositing:
    short: comp
    icon: comp.svg
    order: 8
  ...

bins:
  common:
    _id: uuid
    name: common
    order: 0
  subproject:
    _id: uuid
    name: subproject
    order: 1
  ...

assets:
  asset_name:
    _id: uuid
    name: asset_name
    bin: common
    asset_type: asset
  shot_name:
    _id: uuid
    name: shot_name
    bin: common
    asset_type: shot
  ...
```

### 2. Asset Schema
Since shots and assets are identical in functionality - they are containers for work files and publishes - they can share a single Asset model with an asset_type field that can identify the specific type of Asset it is.

```
_id (uuid) - Id of the asset
project_id (uuid) - UUID of project
name (string) - Name of the asset
created_at (datetime) - Date of creation
created_by (string) - Username
bin (string) - Name of the bin the asset belongs to
asset_type (string) - Type of asset (Shot, Asset, Styleframe...)
tags (list) - List of tags that can be used for filtering
```

## Motivation
Streamline the most important data required to maintain a project and store the most critical data at the project level rather than keeping it nested deeply in the project hierarchy.
